# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' slopeOP
#' @description Optimal partitioning algorithm for change-in-slope problem with a finite number of states (initial and final values of each segment is restricted to a finite set of values)
#' @param data vector of data to segment
#' @param states vector of states = accessible ending values
#' @param penalty the penalty coefficient. A positive number
#' @param type string defining the pruning type to use
#' @return a list of two vectors and a value  = (changepoints, state parameters, global cost)
#' 'changepoints' is the vector of changepoints (we give the last element of each segment)
#' 'states' is the vector of successive final values of each segment (+ the very first value)
#' 'globalCost' is a number equal to the global cost of the penalized changepoint problem
slopeOP <- function(data, states, penalty, type = "null") {
    .Call('_slopeOP_slopeOP', PACKAGE = 'slopeOP', data, states, penalty, type)
}

