# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

slopeOPtransfer <- function(data, states, penalty, constraint = "null", minAngle = 0, type = "channel") {
    .Call('_slopeOP_slopeOPtransfer', PACKAGE = 'slopeOP', data, states, penalty, constraint, minAngle, type)
}

